version: "3.1"
services:
    api:
      build:
        context: ./apps/api/
        dockerfile: Dockerfile
      ports:
        - 4000:4000
      env_file:
        - ./apps/api/.env
      command: ["npm", "run", "start"]
    web:
      build:
        context: ./apps/web/
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      env_file:
        - ./apps/web/.env
      command: ["yarn", "start"]