version: "3.1"
services:
    face-api-graphql:
      build:
        context: ./apps/api/
        dockerfile: Dockerfile
      ports:
        - 4000:4000
      env_file:
      - .env
      command: ["node", "src/server.js"]
